spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/313715295/shop/tree/master/config-repo
server:
  port: 8866
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/